/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crea (o renueva) la sesion de un usuario final anonimo
         * @description Unica ruta que usa la API key. Con `rk_live_` (servidor) o `rk_pub_` (navegador; el `Origin` debe estar en la allowlist del negocio). Devuelve el token de usuario final (30 min) para el resto de rutas. Para renovar sobre el mismo anonimo, enviar el token anterior (aunque haya caducado) en `Authorization: Bearer`.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pregunta al agente del negocio */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de destinos */
        get: operations["listDestinations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/destination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un destino */
        get: operations["getDestination"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pois": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lugares de interes */
        get: operations["listPois"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pois/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detalle de un lugar de interes */
        post: operations["getPoiDetails"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pois/personalized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lugares recomendados para el usuario */
        post: operations["getPersonalizedPois"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rutas turisticas */
        get: operations["listRoutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favourites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marca o desmarca un lugar como favorito */
        post: operations["setFavourite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil del usuario (favoritos) */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connect/lodging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alojamientos conectados */
        get: operations["listLodging"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connect/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paquetes conectados */
        get: operations["listPackages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un paquete */
        get: operations["getPackageDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parada de un paquete por QR */
        get: operations["getPackageStop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convierte una direccion en coordenadas */
        post: operations["geocode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-status/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado de la generacion asincrona de un itinerario */
        get: operations["getPlanStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea un viaje */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Genera el itinerario de un viaje (asincrono) */
        get: operations["generatePlanning"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lee el itinerario de un viaje */
        get: operations["getSchedule"];
        /** Anade una actividad externa al itinerario */
        put: operations["addScheduleActivity"];
        /** Guarda las actividades del itinerario de un viaje */
        post: operations["setSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra preferencias del usuario */
        post: operations["addPreferences"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels/localize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Textos localizados por grupo */
        post: operations["localizeLabels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuracion publica de la app */
        get: operations["getAppConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Success: {
            /** @enum {string} */
            status: "success";
            data?: unknown;
        };
        ErrorItem: {
            type: string;
            msg: string;
        };
        ErrorResponse: {
            /** @enum {string} */
            status?: "error";
            errors: components["schemas"]["ErrorItem"][];
        };
        SessionData: {
            /** @description Token de usuario final. */
            token: string;
            /**
             * @description Segundos de validez.
             * @example 1800
             */
            expires_in: number;
            /** @description Id del usuario anonimo. */
            client_id: number;
            /** @description Configuracion publica del negocio. */
            config?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Validacion fallida */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "address",
                 *           "msg": "address is required"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Sin key, key invalida o revocada, o token invalido, ajeno o de otro tipo */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "token",
                 *           "msg": "Unauthorized Access - No Token Provided!"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Origin no permitido para esta key publicable */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "origin",
                 *           "msg": "Origin not allowed"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Recurso no encontrado (un viaje ajeno o inexistente responde igual) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "task_id",
                 *           "msg": "task not found"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El negocio no tiene agente asignado (solo /chat) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "agent",
                 *           "msg": "No agent is bound to this client"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Error interno */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "generic",
                 *           "msg": "An error occurred! Try again later"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Cuota diaria superada */
        TooManyRequests: {
            headers: {
                /** @description Segundos hasta que se reinicia la cuota (medianoche UTC). */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "quota",
                 *           "msg": "Daily quota exceeded"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Token v4 previo (puede estar caducado) para renovar sobre el mismo usuario anonimo. */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Sesion creada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["SessionData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    question: string;
                    /** @description Identificador de la conversacion; se conserva entre turnos. */
                    session_id?: string;
                    /** @example es */
                    language_code?: string;
                    parameters?: {
                        activity_id?: number;
                    } & {
                        [key: string]: unknown;
                    };
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Respuesta del agente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    listDestinations: {
        parameters: {
            query?: {
                /** @description Filtro por nombre. */
                name?: string;
                /**
                 * @description Filtro de stack.
                 * @example 1
                 */
                stack?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Destinos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getDestination: {
        parameters: {
            query: {
                /**
                 * @description Id del destino.
                 * @example 2
                 */
                destination_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Destino */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    listPois: {
        parameters: {
            query?: {
                /**
                 * @description Etiquetas separadas por coma.
                 * @example generic.local_gem
                 */
                tags?: string;
                /**
                 * @description Destino.
                 * @example 3
                 */
                destination_id?: number;
                /**
                 * @description Incluye destinos cercanos.
                 * @example true
                 */
                include_surrounding_destinations?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lugares de interes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getPoiDetails: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    poi_id: number;
                    /** @example es */
                    language_code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Detalle del POI */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getPersonalizedPois: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    destination_id: number;
                    /** @example es */
                    language_code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Lugares personalizados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    listRoutes: {
        parameters: {
            query?: {
                /**
                 * @description Ids de destino separados por coma (familia explicita).
                 * @example 1,2,3
                 */
                destination_ids?: string;
                /** @description Destino unico. */
                destination_id?: number;
                /**
                 * @description Codigo de idioma (p. ej. es, en).
                 * @example es
                 */
                language_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rutas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    setFavourite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    place_of_interest_id: string;
                    is_favourite?: boolean;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Favorito actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    listLodging: {
        parameters: {
            query: {
                /** @description Destino. */
                destination_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alojamientos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    listPackages: {
        parameters: {
            query: {
                /** @description Destino. */
                destination_id: number;
                /**
                 * @description Codigo de idioma (p. ej. es, en).
                 * @example es
                 */
                language_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paquetes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getPackageDetails: {
        parameters: {
            query: {
                /** @description Id del paquete. */
                package_id: number;
                /**
                 * @description Codigo de idioma (p. ej. es, en).
                 * @example es
                 */
                language_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paquete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getPackageStop: {
        parameters: {
            query: {
                /** @description Codigo QR de la parada. */
                qr: string;
                /**
                 * @description Codigo de idioma (p. ej. es, en).
                 * @example es
                 */
                language_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Parada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    geocode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    address: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Coordenadas (null si la direccion no se reconoce) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            coordinates?: ({
                                latitude?: number;
                                longitude?: number;
                            } & {
                                [key: string]: unknown;
                            }) | null;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getPlanStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id devuelto al pedir el plan. */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado del plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            task_id?: string;
                            status?: string;
                            result?: {
                                [key: string]: unknown;
                            };
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    destination_id: number;
                    /** @default 1 */
                    number_of_people?: number;
                    /** Format: date */
                    start_date?: string;
                    /** Format: date */
                    end_date?: string;
                    trip_purpose?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Viaje creado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            user_trip_id?: number;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    generatePlanning: {
        parameters: {
            query: {
                /**
                 * @description Viaje.
                 * @example 2473
                 */
                user_trip_id: number;
                /**
                 * @description Latitud de partida.
                 * @example -13.8389
                 */
                latitude?: number;
                /**
                 * @description Longitud de partida.
                 * @example -76.25156
                 */
                longitude?: number;
                /**
                 * @description Fuerza las visitas obligatorias.
                 * @example true
                 */
                force_must_visit?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tarea de planificacion (consulta /plan-status/{task_id}) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getSchedule: {
        parameters: {
            query: {
                /**
                 * @description Viaje.
                 * @example 2200
                 */
                user_trip_id: number;
                /**
                 * @description Codigo de idioma (p. ej. es, en).
                 * @example es
                 */
                language_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Itinerario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    addScheduleActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_trip_id: number;
                    external_activity?: {
                        description?: string;
                        start_timestamp?: string;
                        location?: string;
                        external_activity_id?: number;
                    } & {
                        [key: string]: unknown;
                    };
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Actividad anadida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    setSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_trip_id: number;
                    other_activities?: {
                        [key: string]: unknown;
                    }[];
                    poi_activities?: {
                        [key: string]: unknown;
                    }[];
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Itinerario guardado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    addPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default generic */
                    category?: string;
                    tags?: string[];
                    weights?: number[];
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Preferencias registradas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    localizeLabels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    group_code?: string;
                    /** @example es */
                    language_code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Etiquetas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getAppConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuracion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
}
