/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crea (o renueva) la sesion de un usuario final anonimo
         * @description Unica ruta que usa la API key. Con `rbk_live_` (servidor) o `rbk_pub_` (navegador; el `Origin` debe estar en la allowlist del negocio). Devuelve el token de usuario final (30 min) para el resto de rutas. Para renovar sobre el mismo anonimo, enviar el token anterior (aunque haya caducado) en `Authorization: Bearer`.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pregunta al agente del negocio */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de destinos */
        get: operations["listDestinations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/destination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un destino */
        get: operations["getDestination"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pois": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lugares de interes */
        get: operations["listPois"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pois/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detalle de un lugar de interes */
        post: operations["getPoiDetails"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pois/personalized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lugares recomendados para el usuario */
        post: operations["getPersonalizedPois"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rutas turisticas */
        get: operations["listRoutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favourites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marca o desmarca un lugar como favorito */
        post: operations["setFavourite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil del usuario (favoritos) */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connect/lodging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alojamientos conectados */
        get: operations["listLodging"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connect/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paquetes conectados */
        get: operations["listPackages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un paquete */
        get: operations["getPackageDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parada de un paquete por QR */
        get: operations["getPackageStop"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convierte una direccion en coordenadas */
        post: operations["geocode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan-status/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado de la generacion asincrona de un itinerario
         * @description Solo responde al usuario final que recibio ese `task_id` en su chat (mismo negocio). Cualquier otro caso (task_id de otro usuario, de otro negocio o inexistente) responde `404` con el mismo cuerpo.
         */
        get: operations["getPlanStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea un viaje */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Genera el itinerario de un viaje (asincrono) */
        get: operations["generatePlanning"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lee el itinerario de un viaje */
        get: operations["getSchedule"];
        /** Anade una actividad externa al itinerario */
        put: operations["addScheduleActivity"];
        /** Guarda las actividades del itinerario de un viaje */
        post: operations["setSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra preferencias del usuario */
        post: operations["addPreferences"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels/localize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Textos localizados por grupo */
        post: operations["localizeLabels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuracion publica de la app */
        get: operations["getAppConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Success: {
            /** @enum {string} */
            status: "success";
            data?: unknown;
        };
        ErrorItem: {
            type: string;
            msg: string;
        };
        ErrorResponse: {
            /** @enum {string} */
            status?: "error";
            errors: components["schemas"]["ErrorItem"][];
        };
        SessionData: {
            /** @description Token de usuario final. */
            token: string;
            /**
             * @description Segundos de validez.
             * @example 1800
             */
            expires_in: number;
            /** @description Id del usuario anonimo. */
            client_id: number;
            /** @description Configuracion publica del negocio. */
            config?: {
                [key: string]: unknown;
            };
        };
        /** @description Sin campos de datos; el resultado es el `status` de la respuesta. */
        EmptyData: Record<string, never>;
        ImageRefs: {
            image_ref?: string;
            thumb_ref?: string;
        };
        /** @description Atribucion de la imagen (parte de los campos de credito de paquetes y rutas). */
        Credit: {
            credit_author?: string;
            credit_license?: string;
            credit_url?: string;
        };
        /** @description Nodo de destino. `children`/`destinations` repiten este mismo esquema (arbol). */
        Destination: {
            destination_id?: number;
            name?: string;
            parent_destination_id?: number | null;
            is_country?: boolean;
            image_ref?: string;
            thumb_ref?: string;
            flag_ref?: string;
            latitude?: number;
            longitude?: number;
            timezone?: string;
            images?: string[];
            children?: components["schemas"]["Destination"][];
            destinations?: components["schemas"]["Destination"][];
        } & {
            [key: string]: string;
        };
        /** @description Lugar de interes. */
        Poi: {
            place_of_interest_id?: string;
            name?: string;
            category?: string;
            sub_categories?: string[];
            tags?: string[];
            location?: string;
            address?: string;
            latitude?: number;
            longitude?: number;
            entrypoint_latitude?: number;
            entrypoint_longitude?: number;
            destination_id?: number;
            destination_name?: string;
            company_name?: string;
            website?: string;
            phone_number?: string;
            duration?: number;
            visit_start_time?: string;
            matterport_vr_ref?: string;
            matterport_image_ref?: string;
            thumb_ref?: string;
            image_ref?: string;
            images?: string[];
            description?: string;
            short_description?: string;
            availability_hours?: string;
            matterport_description?: string;
            tips?: {
                message?: string;
            }[];
            distance?: number;
            score?: number;
            in_favourites?: boolean;
        };
        RouteStop: {
            tour_stop_id?: number;
            tour_route_id?: number;
            place_of_interest_id?: string;
            order_index?: number;
            name?: string;
            latitude?: number;
            longitude?: number;
            thumb_ref?: string;
            narration?: string;
            description?: string;
            short_description?: string;
            in_favourites?: boolean;
        };
        /** @description Ruta turistica. */
        Route: {
            tour_route_id?: number;
            title?: string;
            location?: string;
            duration?: number;
            tags?: string[];
            destination_id?: number;
            destination_name?: string;
            image_ref?: string;
            thumb_ref?: string;
            credit_author?: string;
            credit_license?: string;
            credit_url?: string;
            description?: string;
            short_description?: string;
            availability_hours?: string;
            stops?: components["schemas"]["RouteStop"][];
            images?: components["schemas"]["ImageRefs"][];
        };
        PersonalizedPoisData: {
            recommended_pois?: components["schemas"]["Poi"][];
            nearby_pois?: components["schemas"]["Poi"][];
            routes?: components["schemas"]["Route"][];
        };
        ProfileData: {
            profile?: {
                favourite_pois?: string[];
                interaction_level?: string;
                total_engagement_points?: number;
                engagement_level_index?: number;
                engagement_level_name?: string;
            };
            preferences?: {
                sub_categories?: string[];
                weights?: number[];
            };
        };
        Lodging: {
            activity_id?: number;
            title?: string;
            thumb_ref?: string;
            image_ref?: string;
            address?: string;
            latitude?: number;
            longitude?: number;
            category?: string;
            subcategory?: string;
            website?: string;
            video_ref?: string;
            company_name?: string;
        };
        LodgingData: {
            lodging?: components["schemas"]["Lodging"][];
        };
        LanguageServed: {
            description?: string;
            short_description?: string;
            label?: string;
            value?: string;
        };
        /** @description Paquete conectado. */
        Package: {
            provider_package_id?: number;
            destination_id?: number;
            name?: string;
            base_language?: string;
            thumb_ref?: string;
            image_ref?: string;
            credit_author?: string;
            credit_license?: string;
            credit_url?: string;
            description?: string;
            stop_count?: number;
            is_unlocked?: boolean;
            language_served?: components["schemas"]["LanguageServed"];
        };
        PackagesData: {
            packages?: components["schemas"]["Package"][];
        };
        /** @description Parada de un paquete. */
        PackageStop: {
            provider_package_stop_id?: number;
            provider_package_id?: number;
            order_index?: number;
            name?: string;
            latitude?: number;
            longitude?: number;
            radius_m?: number;
            thumb_ref?: string;
            image_ref?: string;
            credit_author?: string;
            credit_license?: string;
            credit_url?: string;
            qr_slug?: string;
            description?: string;
            short_description?: string;
            package_name?: string;
            base_language?: string;
            destination_id?: number;
            is_unlocked?: boolean;
            language_served?: components["schemas"]["LanguageServed"];
            facts?: {
                fact_id?: number;
                order_index?: number;
                label?: string;
                value?: string;
                language_served?: components["schemas"]["LanguageServed"];
            }[];
            media?: {
                media_id?: number;
                image_ref?: string;
                thumb_ref?: string;
                credit_author?: string;
                credit_license?: string;
                credit_url?: string;
            }[];
        };
        PackageDetailsData: {
            package?: components["schemas"]["Package"];
            stops?: components["schemas"]["PackageStop"][];
        };
        PackageStopData: {
            stop?: components["schemas"]["PackageStop"];
            unavailable?: boolean;
            package?: {
                provider_package_id?: number;
                name?: string;
            };
        };
        TripCreatedData: {
            user_trip_id?: number;
        };
        /** @description Actividades propuestas para el viaje (POI y ventana horaria). */
        PlanningTaskData: {
            place_of_interest_id?: string;
            start_timestamp?: string;
            end_timestamp?: string;
        }[];
        Leg: {
            distance?: number;
            duration?: number;
            is_approx?: boolean;
        };
        /** @description Actividad de un dia; mezcla POI del viaje y actividades externas (`external_activity_id`). */
        DayActivity: {
            user_poi_activity_id?: number;
            place_of_interest_id?: string;
            destination_id?: number;
            name?: string;
            latitude?: number;
            longitude?: number;
            tags?: string[];
            category?: string;
            sub_categories?: string[];
            description?: string;
            start_timestamp?: string;
            end_timestamp?: string;
            timezone?: string;
            thumb_ref?: string;
            image_ref?: string;
            driving?: components["schemas"]["Leg"];
            walking?: components["schemas"]["Leg"];
            external_activity_id?: number;
            location?: string;
            note?: string;
            color?: string;
        };
        TripSummary: {
            user_trip_id?: number;
            start_date?: string;
            end_date?: string;
            destination_id?: number;
            number_of_people?: number;
            trip_purpose?: string;
            destination?: components["schemas"]["Destination"];
        };
        TripDay: {
            date?: string;
            activities?: components["schemas"]["DayActivity"][];
        };
        ScheduleData: {
            trip?: components["schemas"]["TripSummary"];
            trip_activities?: components["schemas"]["TripDay"][];
            /** @description Solo forma; la API v4 no crea actividades de proveedor. */
            trip_booked_activities?: {
                booked_activities?: {
                    activity_id?: number;
                    checked_in?: boolean;
                    checked_out?: boolean;
                    start_timestamp?: string;
                    end_timestamp?: string;
                }[];
                activities?: {
                    activity_id?: number;
                    title?: string;
                    category?: string;
                    latitude?: number;
                    longitude?: number;
                    duration?: number;
                    timezone_offset?: number;
                    desc?: string;
                    short_desc?: string;
                    images?: string[];
                }[];
            };
        };
        Label: {
            key?: string;
            /** @description Texto en el language_code pedido */
            text?: string;
            /** @description Solo para group_code tag */
            image_ref?: string;
        };
        AppConfigData: {
            partner_gate_enabled?: boolean;
            approved_partners?: string[];
        };
        PlanItem: {
            item_id?: string;
            score?: number;
            meta?: {
                name?: string;
                score?: number;
                time_h?: number;
                category?: string;
                duration?: number;
                location?: string;
                breakfast?: boolean;
                hidden_gem?: boolean;
                locomotion?: string;
                must_visit?: boolean;
                destination?: string;
                distance_km?: number;
                instagrammer?: boolean;
            };
        };
        PlanStatusData: {
            task_id?: string;
            status?: string;
            /** @description Un dia por clave (`day_0`, `day_1`, ...) con sus items. */
            result?: {
                [key: string]: components["schemas"]["PlanItem"][];
            };
        };
        /** @description Accion del agente. Solo salen las acciones listadas en `name`; el resto se descarta. */
        ChatAction: {
            /** @enum {string} */
            name: "speak" | "text" | "redirect" | "raw_data" | "gesture" | "changeRebecaDress";
            /** @description Segun `name`: `speak` {text, language_code}; `text` {text}; `redirect` {destiny}; `gesture` {gestures}; `changeRebecaDress` {destination_id}; `raw_data` {data}, donde `data` (objeto o lista) es la union de los campos de `ChatRawData`. */
            parameters?: {
                text?: string;
                language_code?: string;
                destiny?: string;
                gestures?: string[];
                destination_id?: number;
                data?: components["schemas"]["ChatRawData"] | components["schemas"]["ChatRawData"][];
            };
        };
        /** @description Contenido de una accion `raw_data` (fichas de destino, plan asincrono, POI, alojamiento, itinerario). */
        ChatRawData: {
            title?: string;
            text?: string;
            description?: string;
            image?: string;
            images?: string[];
            thumb_ref?: string;
            thumb_refs?: string[];
            video_ref?: string;
            video_refs?: string[];
            videos?: string[];
            /** @description Id para consultar `GET /plan-status/{task_id}`. */
            task_id?: string;
            status?: string;
            destination_id?: number;
            categories?: string[];
            tags?: string[];
            pois?: components["schemas"]["Poi"][];
            accommodation_name?: string;
            accommodation_code?: string;
            accommodation_description?: string;
            accommodation_spaces?: number;
            accommodation_items?: string[];
            price?: number;
            availability?: boolean;
            latitude?: number;
            longitude?: number;
            trip?: components["schemas"]["TripSummary"];
            trip_activities?: components["schemas"]["TripDay"][];
            plan?: {
                trip?: components["schemas"]["TripSummary"];
                trip_activities?: components["schemas"]["TripDay"][];
            };
        };
        /** @description Respuesta del agente. Solo salen los campos listados. */
        ChatData: {
            actions?: components["schemas"]["ChatAction"][];
            /** @description Identificador del hilo de la conversacion. */
            thread_id?: string;
        };
    };
    responses: {
        /** @description Validacion fallida */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "address",
                 *           "msg": "address is required"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Sin key, key invalida o revocada, o token invalido, ajeno o de otro tipo */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "token",
                 *           "msg": "Unauthorized Access - No Token Provided!"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Origin no permitido para esta key publicable */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "origin",
                 *           "msg": "Origin not allowed"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Recurso no encontrado (un viaje o task_id ajeno o inexistente responde igual) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "task_id",
                 *           "msg": "task not found"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El negocio no tiene agente asignado (solo /chat) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "agent",
                 *           "msg": "No agent is bound to this client"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Error interno */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "generic",
                 *           "msg": "An error occurred! Try again later"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Cuota diaria superada (5000/dia por negocio para claves publicables sin cuota propia) */
        TooManyRequests: {
            headers: {
                /** @description Segundos hasta que se reinicia la cuota (medianoche UTC). */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "status": "error",
                 *       "errors": [
                 *         {
                 *           "type": "quota",
                 *           "msg": "Daily quota exceeded"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Token v4 previo (puede estar caducado) para renovar sobre el mismo usuario anonimo. */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Sesion creada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["SessionData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    question: string;
                    /** @description Identificador de la conversacion; se conserva entre turnos. */
                    session_id?: string;
                    /** @example es */
                    language_code?: string;
                    parameters?: {
                        activity_id?: number;
                    } & {
                        [key: string]: unknown;
                    };
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Respuesta del agente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["ChatData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    listDestinations: {
        parameters: {
            query?: {
                /** @description Filtro por nombre. */
                name?: string;
                /**
                 * @description Filtro de stack.
                 * @example 1
                 */
                stack?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Destinos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["Destination"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getDestination: {
        parameters: {
            query: {
                /**
                 * @description Id del destino.
                 * @example 2
                 */
                destination_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Destino */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["Destination"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    listPois: {
        parameters: {
            query?: {
                /**
                 * @description Etiquetas separadas por coma.
                 * @example generic.local_gem
                 */
                tags?: string;
                /**
                 * @description Destino.
                 * @example 3
                 */
                destination_id?: number;
                /**
                 * @description Incluye destinos cercanos.
                 * @example true
                 */
                include_surrounding_destinations?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lugares de interes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["Poi"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getPoiDetails: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    poi_id: number;
                    /** @example es */
                    language_code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Detalle del POI */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["Poi"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getPersonalizedPois: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    destination_id: number;
                    /** @example es */
                    language_code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Lugares personalizados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["PersonalizedPoisData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    listRoutes: {
        parameters: {
            query?: {
                /**
                 * @description Ids de destino separados por coma (familia explicita).
                 * @example 1,2,3
                 */
                destination_ids?: string;
                /** @description Destino unico. */
                destination_id?: number;
                /**
                 * @description Codigo de idioma (p. ej. es, en).
                 * @example es
                 */
                language_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rutas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["Route"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    setFavourite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    place_of_interest_id: string;
                    is_favourite?: boolean;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Favorito actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["EmptyData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["ProfileData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    listLodging: {
        parameters: {
            query: {
                /** @description Destino. */
                destination_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alojamientos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["LodgingData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    listPackages: {
        parameters: {
            query: {
                /** @description Destino. */
                destination_id: number;
                /**
                 * @description Codigo de idioma (p. ej. es, en).
                 * @example es
                 */
                language_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paquetes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["PackagesData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getPackageDetails: {
        parameters: {
            query: {
                /** @description Id del paquete. */
                package_id: number;
                /**
                 * @description Codigo de idioma (p. ej. es, en).
                 * @example es
                 */
                language_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paquete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["PackageDetailsData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getPackageStop: {
        parameters: {
            query: {
                /** @description Codigo QR de la parada. */
                qr: string;
                /**
                 * @description Codigo de idioma (p. ej. es, en).
                 * @example es
                 */
                language_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Parada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["PackageStopData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    geocode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    address: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Coordenadas (null si la direccion no se reconoce) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: {
                            coordinates?: ({
                                latitude?: number;
                                longitude?: number;
                            } & {
                                [key: string]: unknown;
                            }) | null;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getPlanStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id que el agente devolvio en el chat de este usuario (accion `raw_data`). */
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado del plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["PlanStatusData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    destination_id: number;
                    /** @default 1 */
                    number_of_people?: number;
                    /** Format: date */
                    start_date?: string;
                    /** Format: date */
                    end_date?: string;
                    trip_purpose?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Viaje creado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["TripCreatedData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    generatePlanning: {
        parameters: {
            query: {
                /**
                 * @description Viaje.
                 * @example 2473
                 */
                user_trip_id: number;
                /**
                 * @description Latitud de partida.
                 * @example -13.8389
                 */
                latitude?: number;
                /**
                 * @description Longitud de partida.
                 * @example -76.25156
                 */
                longitude?: number;
                /**
                 * @description Fuerza las visitas obligatorias.
                 * @example true
                 */
                force_must_visit?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Actividades propuestas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["PlanningTaskData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getSchedule: {
        parameters: {
            query: {
                /**
                 * @description Viaje.
                 * @example 2200
                 */
                user_trip_id: number;
                /**
                 * @description Codigo de idioma (p. ej. es, en).
                 * @example es
                 */
                language_code?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Itinerario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["ScheduleData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    addScheduleActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_trip_id: number;
                    external_activity?: {
                        description?: string;
                        start_timestamp?: string;
                        location?: string;
                        external_activity_id?: number;
                    } & {
                        [key: string]: unknown;
                    };
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Actividad anadida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["EmptyData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    setSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_trip_id: number;
                    other_activities?: {
                        [key: string]: unknown;
                    }[];
                    poi_activities?: {
                        [key: string]: unknown;
                    }[];
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Itinerario guardado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["EmptyData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    addPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default generic */
                    category?: string;
                    tags?: string[];
                    weights?: number[];
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Preferencias registradas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["EmptyData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    localizeLabels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    group_code?: string;
                    /** @example es */
                    language_code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Etiquetas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["Label"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
    getAppConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuracion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"] & {
                        data?: components["schemas"]["AppConfigData"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["ServerError"];
        };
    };
}
